# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: my-first-flow-tags-edition

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Collecting tag data
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            nagyjames/project4
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
            # tags: nagyjames/project4:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  discord-hook:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Send message to webhook on Discord
        uses: johnnyhuy/actions-discord-git-webhook@main
        with: webhook_url: ${{ secrets.DISCORD_URL }}
